version: '3'
services:
  frontend:
    build: ./frontend # Path to your frontend directory
    ports:
      - "3000:80" # Map frontend port to port 80 inside the container
    networks:
      - app-network

  backend:
    build: ./backend # Path to your backend directory
    ports:
      - "5003:5003" # Map backend port
    environment:
      NODE_ENV: production
      # Add any environment variables here
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
